version: "3.9"

services:
  kong-migrations:
    build:
      context: .
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: ${NEON_PG_HOST}
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: ${NEON_PG_DATABASE}
      KONG_PG_USER: ${NEON_PG_USER}
      KONG_PG_PASSWORD: ${NEON_PG_PASSWORD}
      KONG_PG_SSL: "on"
      KONG_PG_SSL_VERIFY: "off"
      KONG_PLUGINS: "bundled,kong-openid-connect"
    command: >
      sh -ec '
        kong migrations bootstrap --vv || true &&
        kong migrations up --vv &&
        kong migrations finish --vv
      '
    restart: "no"

  kong-gateway:
    build:
      context: .
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: ${NEON_PG_HOST}
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: ${NEON_PG_DATABASE}
      KONG_PG_USER: ${NEON_PG_USER}
      KONG_PG_PASSWORD: ${NEON_PG_PASSWORD}
      KONG_PG_SSL: "on"
      KONG_PG_SSL_VERIFY: "off"

      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "off"
      KONG_ADMIN_GUI_LISTEN: "off"

      KONG_PLUGINS: "bundled,kong-openid-connect"
    expose:
      - "8000"
    restart: unless-stopped

  kong-admin:
    build:
      context: .
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: ${NEON_PG_HOST}
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: ${NEON_PG_DATABASE}
      KONG_PG_USER: ${NEON_PG_USER}
      KONG_PG_PASSWORD: ${NEON_PG_PASSWORD}
      KONG_PG_SSL: "on"
      KONG_PG_SSL_VERIFY: "off"

      KONG_PROXY_LISTEN: "off"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"

      KONG_ADMIN_GUI_URL: "https://manager-kong.api.cloud.hablou.com.br"
      KONG_ADMIN_GUI_API_URL: "https://kong.api.cloud.hablou.com.br"

      KONG_PLUGINS: "bundled,kong-openid-connect"
    expose:
      - "8001"
      - "8002"
    restart: unless-stopped
